- database/console/model_make_command.go
- database/console/model_make_command_test.go
- database/console/stubs.go
- database/service_provider.go
- http/console/controller_make_command.go
- http/console/controller_make_command_test.go
- http/console/middleware_make_command.go
- http/console/middleware_make_command_test.go
- http/console/stubs.go
- http/service_provider.go
I have implemented the following Artisan commands to simplify the development process:
- make:controller: generates a new controller with the specified name.
- make:middleware: generates a new middleware with the specified name.
- make:model: generates a new model with the specified name.
> Adding Artisan Commands for Generating Controllers, Middlewares, and Models

- contracts/http/rate_limiter.go
- facades/http.go
- http/limit/limit.go
- http/middleware/throttle.go
- http/rate_limiter.go
- http/service_provider.go
The expected usage goal in `goravel/goravel` is：
1. Add `configureRateLimiting` method and RateLimiter configurations to `app/providers/route_service_provider.go`；
```
func (receiver *RouteServiceProvider) configureRateLimiting() {
facades.RateLimiter.For("global", func(ctx contractshttp.Context) contractshttp.Limit {
return limit.PerMinute(1)
})
facades.RateLimiter.ForWithLimits("upload", func(ctx contractshttp.Context) []contractshttp.Limit {
return []contractshttp.Limit{limit.PerMinute(1), limit.PerDays(2, 3).By("1").Response(func(ctx contractshttp.Context) {
ctx.Request().AbortWithStatusJson(499, contractshttp.Json{
"Hi": "Goravel",
})
})}
})
}
```
2. Add middleware to`route/web.go`：
```
facades.Route.Middleware(middleware.Throttle("global"), middleware.Throttle("upload"))
```
> HTTP Throttle middleware

- contracts/http/request.go
- http/console/stubs.go
- http/gin_request.go
- route/gin_test.go
- support/str/str.go
- support/str/str_test.go
- validation/options.go
- validation/validation.go
- validation/validation_test.go
Add `ctx http.Context` parameter to the methods under `request`: `Rules`, `Messages`, `Attributes`, `PrepareForValidation`, allows you to do more custom configurations.
> Feat: Add ctx parameter to the methods under request

- hash/application_test.go
- hash/argon2id.go
> fix: argon2id configuration override

- contracts/database/orm/mocks/Query.go
- contracts/database/orm/mocks/Transaction.go
- contracts/database/orm/orm.go
- database/gorm/gorm.go
- database/gorm/gorm_test.go
- database/gorm/hints/with_hint.go
Close https://github.com/goravel/goravel/issues/101
> Add Lock methods for facades.Orm

- contracts/http/request.go
- http/gin_request.go
> feat: Add Host method

- http/gin_request.go
Close https://github.com/goravel/goravel/issues/129
> Fix: [#129] ctx.Request().Header( key: token) will panic

- foundation/application.go
- foundation/console/package_make_command.go
- foundation/console/package_make_command_stubs.go
- foundation/console/package_make_command_test.go
```
go run . artisan make:package sms
```
> Feat: Add make package command

- route/gin.go
Close: https://github.com/goravel/goravel/issues/139
> Fix: [#139] Optimize HTTP print

- database/console/driver/sqlite.go
- database/console/migrate_command.go
- database/console/migrate_command_test.go
- database/console/migrate_creator.go
- database/console/migrate_fresh_command.go
- database/console/migrate_fresh_command_test.go
- database/console/migrate_make_command.go
- database/console/migrate_refresh_command.go
- database/console/migrate_refresh_command_test.go
- database/console/migrate_reset_command.go
- database/console/migrate_reset_command_test.go
- database/console/migrate_rollback_command.go
- database/console/migrate_rollback_command_test.go
- database/console/migrate_status_command.go
- database/console/migrate_status_command_test.go
- database/console/migrate_stubs.go
- database/console/table_guesser.go
- database/service_provider.go
Closes goravel/goravel#50
Add `refresh`  `fresh`  `reset`  `status` command for migrate.
none.
> feat: add methods for migrate

- validation/validation_test.go
- validation/validator.go
Validation should ignore when a field is empty and is not required
> Fix: Validation should ignore when a field is empty and is not required

- support/database/database.go
- support/database/database_test.go
Closes [ [Bug] Trying to lazy eager load relation is not working ](https://github.com/goravel/goravel/issues/205)
I found Lazy Eager Loading was not working when using UUID primary keys, after debugging I found this change solves the issue but not sure about the implications this may have or if there is any better workaround.
> fix: Tentative fix for Lazy Eager Loading with uuids

- .gitignore
- contracts/foundation/service_provider.go
- contracts/foundation/service_provider_test.go
Adding a predefined ServiceProvider allows you to omit some implementations when defining a ServiceProvider.
The idea came from GRPC `UnimplementedTestServiceServer`.
See: https://github.com/goravel/framework/blob/master/grpc/test.pb.go#L191
**Before:**
```go
package hash
import (
"github.com/goravel/framework/contracts/foundation"
)
const Binding = "goravel.hash"
type ServiceProvider struct {
}
func (hash *ServiceProvider) Register(app foundation.Application) {
app.Singleton(Binding, func(app foundation.Application) (any, error) {
return NewApplication(app.MakeConfig()), nil
})
}
func (hash *ServiceProvider) Boot(app foundation.Application) {
}
```
**But now:**
```go
package hash
import (
"github.com/goravel/framework/contracts/foundation"
)
const Binding = "goravel.hash"
type …
```
> feat: Add a predefined ServiceProvider

- support/debug/dump.go
- support/debug/dump_test.go
Alias `spew.Dump` and so on.
- `debug.Dump()`
- `debug.SDump()`
- `debug.FDump()`
> feat: Alias `spew.Dump` and so on

- auth/console/jwt_secret_command.go
- config/service_provider.go
- console/console/key_generate_command.go
- foundation/application.go
- support/constant.go
key make command support custom env path
> feat: key make support custom env path

- http/console/controller_make_command.go
- http/console/controller_make_command_test.go
- http/console/stubs.go
This MR adds a `--resource` flag to the make controller command.
> feat: add resource flag to make:controller

- auth/auth.go
- auth/auth_test.go
Closes https://github.com/goravel/goravel/issues/239
> fix: [#239] [Bug] The JWT token will be expired immediately when ttl == 0

- database/gorm/event.go
- database/gorm/event_test.go
- database/gorm/query.go
- database/gorm/query_test.go
- database/gorm/utils.go
- database/gorm/utils_test.go
- support/database/database.go
- support/database/database_test.go
> fix: will panic when model contains a private field

- log/logrus_writer.go
Closes https://github.com/goravel/goravel/issues/244
Before:
After:
> feat: The trace printed by facades.Log().Error uses reverse order

- config/application.go
- config/application_test.go
Closes https://github.com/goravel/goravel/issues/265
We can set APP_KEY by `APP_KEY=123 go run .` instead of setting it in the .env file. The configuration variables read order is system environment > .env > config files.
> feat: [#265] The Config module supports get system environment variables

- validation/validation.go
- validation/validation_test.go
- validation/validator.go
- validation/validator_test.go
> fix: Validator Bind can't cast value

- auth/auth_test.go
- contracts/http/context.go
- http/context.go
- http/context_test.go
- http/middleware/throttle_test.go
- mocks/http/Context.go
> feat: Add SetContext method to set the context 

- contracts/log/log.go
- log/formatter/general.go
- log/logrus_writer.go
- log/logrus_writer_test.go
- mocks/log/Log.go
- mocks/log/Writer.go
- testing/mock/log.go
Closes: 
https://github.com/goravel/goravel/issues/330 
https://github.com/goravel/goravel/issues/332
> fix: The trace of Log doesn't make a new line when calling with the Request method

- log/logrus_writer.go
Closes https://github.com/goravel/goravel/issues/335
> fix: facades.Log().Tags() does not clear tags after writing the log

- contracts/mail/mail.go
- mail/application.go
- mail/application_test.go
- mocks/mail/Mail.go
Closes https://github.com/goravel/goravel/issues/328
> feat: The Queue method of the Mail module doesn't need to pass a paramter

- contracts/http/cookie.go
- contracts/http/request.go
- contracts/http/response.go
- http/middleware/throttle_test.go
- log/logrus_writer_test.go
- mocks/http/ContextRequest.go
- mocks/http/ContextResponse.go
Closes https://github.com/goravel/goravel/issues/271
> feat: The HTTP module supports set Cookie

- auth/auth.go
- auth/auth_test.go
- auth/service_provider.go
- contracts/auth/auth.go
- contracts/foundation/container.go
- facades/auth.go
- foundation/application_test.go
- foundation/container.go
- mocks/auth/Auth.go
- mocks/foundation/Application.go
- mocks/foundation/Container.go
Closes https://github.com/goravel/goravel/issues/329
> feat: Context can be passed to facades.Auth() directly, and other methods of Auth don't need to pass Contect anymore

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add WhereIn method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
Add OrWhereNotIn and WhereNotIn methods
> feat: add OrWhereNotIn and WhereNotIn methods

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add OrderByDesc method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add WhereBetween method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add OrderBy method

- contracts/database/orm/constants.go
- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add InRandomOrder method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add WhereNotBetween method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- database/gorm/test_utils.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add WhereNull method

- testing/mock/mock.go
> feat: Optimize testing  mock

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add WhereNotNull method

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
add OrWhereBetween and OrWhereNotBetween methods
> feat: add OrWhereBetween and OrWhereNotBetween methods

- contracts/database/orm/orm.go
- database/gorm/query.go
- database/gorm/query_test.go
- mocks/database/orm/Query.go
- mocks/database/orm/Transaction.go
> feat: add Exists method

- config/application_test.go
- database/gorm/conditions.go
- database/gorm/cursor.go
- database/gorm/event.go
- database/gorm/event_test.go
- database/gorm/query.go
- database/gorm/query_test.go
- database/gorm/test_models.go
- database/gorm/test_utils.go
- database/gorm/transaction.go
- database/gorm/wire.go
- database/gorm/wire_gen.go
- database/orm.go
- database/wire_gen.go
- go.mod
- log/formatter/general.go
- queue/application_test.go
- queue/task.go
- support/constant.go
- support/docker/database.go
- testing/mock/log.go
> chore: Merge v1.13

- database/orm/model.go
Closes [#382](https://github.com/goravel/goravel/issues/382)
Add JSON tags to models
> feat: add json tags to models

- auth/auth.go
- auth/auth_test.go
Closes https://github.com/goravel/goravel/issues/388
> fix: [#388] [Bug] data error when calling facades.Auth().Parse() multiple times with different guard

- database/gorm/event.go
- database/gorm/query.go
- database/orm.go
- database/orm_test.go
Closes https://github.com/goravel/goravel/issues/390
> fix: [#390] The context that set by facades.Orm().WithContext() isn't passed to orm events

- log/logrus_writer.go
- log/logrus_writer_test.go
Closes https://github.com/goravel/goravel/issues/402
> fix: The traces don't cleaned when calling Log.Info after Log.Error

- translation/service_provider.go
- translation/translator_test.go
There is an issue when calling `facades.Lang().SetLocale` in middle, `facades.Lang().CurrentLocale()` still returns the default locale in controller.
> fix: translation issue

- session/middleware/start_session.go
The session can't be set correctly after `req.Next()` in Gin and Fiber.
> fix: a session middleware issue

- contracts/http/response.go
- http/middleware/throttle_test.go
- log/logrus_writer_test.go
- mocks/http/ContextResponse.go
- mocks/http/ResponseStatus.go
- session/middleware/start_session_test.go
RelatedTo https://github.com/goravel/goravel/issues/449
> feat: [#449] Implement HTTP response stream 

- contracts/validation/validation.go
- mocks/validation/Validation.go
- validation/validation.go
- validation/validation_test.go
> feat: Remove `AddFilter` method from validation facade

- contracts/route/route.go
- mocks/route/Route.go
[Closes https://github.com/goravel/goravel/issues/436](https://github.com/goravel/goravel/issues/436)
> feat: add Shutdown to support graceful quit of HTTP Server

- contracts/route/route.go
- mocks/route/Route.go
The ctx is unnecessary, change it to `...context.Context`. @zxdstyle
> feat: optimize the ctx parameter

- contracts/route/route.go
- mocks/route/Route.go
Remove `route.Shutdown`, use `route.Stop` directly.
> feat: remove route.Shutdown

- database/factory.go
- database/gorm/cursor.go
- go.mod
- go.sum
- support/docker/database.go
- support/docker/sqlserver.go
- support/docker/sqlserver_test.go
- testing/docker/database_test.go
- validation/validation_test.go
- validation/validator.go
Closes https://github.com/goravel/goravel/issues/533
> fix: [#533] there is a bug when validating nested data

- config/application.go
0 stands for exit successfully, 1 stands for exit with error.
> feat: optimize exit to 0 from 1

- database/console/show_command.go
- database/console/show_command_test.go
- database/service_provider.go
This PR introduces an `artisan db:show` command to display database information.
> feat: Add artisan db:show command

- console/application.go
- contracts/console/command/command.go
- database/console/table_command.go
- database/console/table_command_test.go
- database/service_provider.go
This PR introduces an artisan `db:table` command to display table information.
> feat: Add artisan db:table command

- support/color/print.go
- support/color/print_test.go
Package color provides utilities for rendering and printing colorized text using color tags.
The color tags are automatically parsed and rendered.
Supported Features:
1. Style Tags:
Use predefined style tags to format text. Example:
`color.Print("<suc>he</><comment>llo</>, <cyan>wel</><red>come</>")`
2. Custom Color Attributes:
Use specific color attributes for more granular control. Example:
` color.Println("<fg=11aa23>he</><bg=120,35,156>llo</>, <fg=167;bg=232>wel</><fg=red>come</>")`
Color tag more detail in https://gookit.github.io/color/#/?id=html-like-tag-usage
> feat: add color printing utilities

- console/application.go
- console/application_test.go
- console/cli_helper_test.go
- console/service_provider.go
> fix: artisan bug

- contracts/database/schema/column.go
- contracts/database/schema/grammar.go
- database/schema/blueprint.go
- database/schema/blueprint_test.go
- database/schema/column.go
- database/schema/column_test.go
- database/schema/constants/constants.go
- database/schema/grammars/mysql.go
- database/schema/grammars/mysql_test.go
- database/schema/grammars/postgres.go
- database/schema/grammars/postgres_test.go
- database/schema/grammars/sqlite.go
- database/schema/grammars/sqlserver.go
- database/schema/grammars/sqlserver_test.go
- database/schema/schema_test.go
- mocks/database/schema/ColumnDefinition.go
- mocks/database/schema/Grammar.go
Go migrator support to change table column
```go
func (r *M20250108083539UpdateTestTable) Up() error {
return facades.Schema().Table("test", func(table schema.Blueprint) {
table.String("votes", 120).Comment("tes change").Change()
})
}
```
Closes https://github.com/goravel/goravel/issues/541
> feat: migrator support to change table column

- auth/auth_test.go
- contracts/database/schema/blueprint.go
- database/schema/blueprint.go
- database/schema/grammars/utils.go
- database/schema/grammars/utils_test.go
- database/schema/schema_test.go
- mocks/database/schema/Blueprint.go
Go Migrator Support for Custom Column Types,like 
```go
table.Column("geometry", "geometry").Comment("This is a geometry column")
```
Closes https://github.com/goravel/goravel/issues/579
Resolve https://github.com/goravel/goravel/issues/568
> feat: [#579] Go Migrator Support Custom Column Types

- auth/service_provider.go
- cache/service_provider.go
- config/binding.go
- config/service_provider.go
- console/service_provider.go
- contracts/binding.go
- crypt/service_provider.go
- database/orm/orm.go
- database/schema/schema.go
- database/seeder/seeder.go
- database/service_provider.go
- event/service_provider.go
- filesystem/service_provider.go
- foundation/application_test.go
- foundation/container.go
- grpc/service_provider.go
- hash/service_provider.go
- http/service_provider.go
- log/service_provider.go
- mail/service_provider.go
- queue/service_provider.go
- route/service_provider.go
- schedule/service_provider.go
- session/service_provider.go
- testing/service_provider.go
- translation/service_provider.go
- validation/service_provider.go
Normal binding for internal packages will include the package even we never registered it in app because of Make func in container which make the output file larger, so we need a diff. way to bind these packages and keep Make functions in container
fresh goravl contains all service providers
```bash
➜  goravel git:(v1.15.x) ✗ go build -o goravel main.go    
➜  goravel git:(v1.15.x) ✗ ll
total 152304
-rw-r--r--@  1 ahmed3mar  staff   550B Feb  7 10:01 Dockerfile
-rw-r--r--@  1 ahmed3mar  staff   1.0K Feb  7 10:01 LICENSE
-rw-r--r--@  1 ahmed3mar  staff   9.2K Feb  7 10:01 README.md
-rw-r--r--@  1 ahmed3mar  staff   9.0K Feb  7 10:01 README_zh.md
drwxr-xr-x@  7 ahmed3mar  staff   224B Feb  7 10:01 app
drwxr-xr-x@  3 …
```
> feat: Move bindings to config

- support/database/database.go
- support/database/database_test.go
I found an error while working with the model.
link problem with the GetIDByReflect method. This method does not properly handle submodel with id string. 
Also, this method does not process variants with double nesting.
The problem is here, not in nested fields it works correctly
```
cast.ToString(id) == "" || cast.ToInt(id) == 0
```
The problem with such models
```
type User struct {
TestStructString
Name string
}
ts := User{Name: "name"}
ts.ID = "testId"
```
And with nested models
```
type UserFirst struct {
TestStructString
Name string
}
type UserSecond struct {
UserFirst
Avatar string
}
ts := UserSecond{}
ts.ID = "testId"
```
And I also refactored this method a little
> fix: Problem with submodels id string

- contracts/database/db/db.go
- database/db/db.go
- database/db/db_test.go
- database/service_provider.go
- mocks/database/db/DB.go
- tests/db_test.go
- tests/query.go
> feat: [#358] Add connection method for DB

- contracts/database/orm/orm.go
- database/console/show_command.go
- database/console/show_command_test.go
- database/gorm/query.go
- mocks/database/orm/Query.go
- tests/query_test.go
- tests/schema_test.go
Closes https://github.com/goravel/goravel/issues/614
> feat: [#614] Optimize facades.Orm().Query().Exists(), Order() and Count() methods

- contracts/database/db/db.go
- database/db/db.go
- database/db/db_test.go
- database/db/query.go
- database/db/query_test.go
- database/db/utils.go
- errors/list.go
- mocks/database/db/DB.go
- tests/db_test.go
- tests/query.go
> feat: [#358] Implement Transaction methods

- contracts/foundation/application.go
- foundation/application.go
- foundation/application_test.go
- mocks/foundation/Application.go
- support/path/path.go
This PR aims to add the Path Helper function for the resource path which would target the `resources/*` directory.
```golang
path.Resource("js/app.js")
```
> feat: Add Resource Path

- database/db/query.go
- database/db/to_sql.go
- database/logger/logger.go
- tests/db_test.go
- tests/models.go
- tests/query_test.go
- tests/table.go
> feat: optimize DB performance

- http/service_provider.go
- http/view.go
> chore: improve path concatenation for better readability

- database/gorm/query.go
- tests/query_test.go
Closes https://github.com/goravel/goravel/issues/646
```go
facades.Orm().Query().Where(func(query orm.Query) orm.Query {
return query.Where("name != ?", "admin")
}).FindOrFail(&user, 100)
```
> feat: [#646] The Where function of Orm supports func condition

- database/gorm/query.go
- tests/query_test.go
> Revert "feat: [#646] The Where function of Orm supports func condition"

- console/application.go
- console/application_test.go
- console/cli_context.go
- console/cli_helper.go
- console/cli_helper_test.go
- go.mod
- go.sum
- support/color/color.go
Closes https://github.com/goravel/goravel/issues/653
> feat: [#653] Update github.com/urfave/cli/v2 to v3

- support/carbon/carbon.go
- support/carbon/carbon_test.go
Add SetLocation and SetLocale methods and unit test cases
> feat: Add SetLocation and SetLocale methods and unit test cases

- contracts/database/migration/migrator.go
- contracts/packages/modify/modify.go
- database/console/migration/migrate_make_command.go
- database/console/migration/migrate_make_command_test.go
- database/console/seeder_make_command.go
- database/console/seeder_make_command_test.go
- database/console/stubs.go
- database/migration/migrator.go
- database/migration/migrator_test.go
- errors/list.go
- foundation/console/package_make_command_stubs.go
- mocks/database/migration/Migrator.go
- mocks/packages/modify/GoFile.go
- packages/modify/actions_test.go
- packages/modify/modify.go
- packages/modify/modify_test.go
- support/console/console.go
- support/console/console_test.go
Closes https://github.com/goravel/goravel/issues/649
This change improves workflow efficiency by automatically registering migration and seeder files created via artisan `make:migration` and `artisan make:seeder`.
These files are now injected into database/kernel.go, eliminating the need for manual inclusion and streamlining the setup process.
> feat: [#649]  auto-register migration and seeder when created via CLI

- contracts/schedule/schedule.go
- mocks/schedule/Schedule.go
- schedule/application.go
- schedule/console/list_command.go
- schedule/console/list_command_test.go
- schedule/console/run_command.go
- schedule/console/run_command_test.go
- schedule/event.go
- schedule/event_test.go
- schedule/service_provider.go
Closes https://github.com/goravel/goravel/issues/534
This PR adds two new Artisan commands:
- schedule:run: Starts the internal scheduler and runs all due tasks.
- schedule:list: Lists all registered scheduled tasks.
Goravel has a built-in task scheduling system based on [robfig/cron](https://github.com/robfig/cron), a robust and flexible cron engine for Go.
Thanks to this internal scheduler, there is no need to rely on the system’s crontab to trigger scheduled tasks. We can manage task execution entirely within the application by keeping the schedule:run process alive.
We only need to:
- Run artisan schedule:run as the main process in a Docker container, or
- Use a process manager like supervisord, systemd, or pm2 to ensure the schedule:run process remains running.
This approach provides …
> feat: [#534] add schedule:run and schedule:list commands

- foundation/console/package_make_command_stubs.go
- packages/modify/actions.go
- packages/modify/actions_test.go
- packages/modify/utils.go
- packages/modify/utils_test.go
This change adds a check to ensure that an import is actually unused before it is removed from the source file.
It prevents accidentally deleting shared imports that are still required by other packages.
For example, multiple filesystem drivers like `github.com/goravel/cloudinary` and `github.com/goravel/minio` may each import `github.com/goravel/framework/contracts/filesystem`. When both are installed, this import is shared. If one of them is uninstalled, we should not remove the shared import unless it is truly unused.
This fix avoids such cases by checking whether the import alias is still referenced in the AST before removing it.
> chore: ensure imports are unused before removing

- database/gorm/query.go
- tests/query.go
- tests/query_test.go
Closes https://github.com/goravel/goravel/issues/660
This pull request includes updates to the `Query` methods in the `database/gorm/query.go` file to improve SQL query parameterization, as well as changes to the test suite in `tests/query.go` and `tests/query_test.go` to adjust test behavior and add new test cases for date-based filtering. Below are the most important changes grouped by theme:
* Updated the `WhereBetween`, `WhereNotBetween`, `OrWhereBetween`, and `OrWhereNotBetween` methods in `database/gorm/query.go` to use parameterized queries with placeholders (`?`) instead of directly embedding values in the SQL string. This change enhances security by preventing SQL injection and improves query performance.
* Commented out the initialization of MySQL, SQL Server, and SQLite test …
> fix: [#660] WhereBetween, etc. method can't support string correctly

- packages/setup.go
`filepath.Dir` returns `\` as a path separator on Windows, which leads to invalid Go import paths when writing module paths into source files (e.g. during `package:install`). Replacing it with `path.Dir` ensures `/` is always used, as required by Go import syntax. This issue only affects Windows systems.
> fix: module path separator on Windows

- database/migration/migrator.go
- database/migration/migrator_test.go
- tests/migrator_test.go
This pull request enhances the `Migrator` functionality by adding checks for the existence of the migration repository and improves test coverage for the `Reset` and `Rollback` methods. Key changes include adding repository existence checks in the `Reset` and `Rollback` methods, updating test cases to handle these scenarios, and verifying behavior when the repository does not exist.
* Added a check in `Reset` to verify if the migration repository exists. If it does not, a warning is logged, and the method exits early. (`database/migration/migrator.go`, [database/migration/migrator.goR60-R65](diffhunk://#diff-f8d858a2d874212813f0762d22b0310413ce5972f6439bc386e8cd28cf3d1091R60-R65))
* Added a similar repository existence check in `Rollback` to ensure the method exits early if the repository …
> fix: migration reset and rollback

- contracts/route/route.go
- mocks/route/Route.go
Closes https://github.com/goravel/goravel/issues/632
This pull request introduces a new method, `GetRoutes`, to the `Route` interface in `contracts/route/route.go` for retrieving all registered routes, along with its implementation in the mock `Route` object in `mocks/route/Route.go`. Additionally, it defines a new `RouteInfo` struct to encapsulate route metadata such as method, path, and handler.
* **Added `GetRoutes` method to `Route` interface**: Enables retrieval of all registered routes in the router.
* **Introduced `RouteInfo` struct**: Represents metadata for routes, including HTTP method, path, and handler name.
* **Implemented `GetRoutes` in mock `Route`**: Provides a mock function for testing the `GetRoutes` method, including helper methods like `Return` and `RunAndReturn` for …
> feat: [#632] Add GetRoutes method

- go.mod
- go.sum
- tests/db_test.go
- tests/go.mod
- tests/go.sum
- tests/mock_config.go
- tests/query.go
- tests/query_test.go
Closes https://github.com/goravel/goravel/issues/706
This pull request introduces several changes to the database testing and configuration logic, focusing on simplifying the `mockDatabaseConfig` function, improving timezone handling, and enhancing test query builders. Key updates include refactoring function signatures, adding timezone support, and introducing a new test for timezone functionality.
* [`tests/mock_config.go`](diffhunk://#diff-e99a73045ad79e1cf1d850b270fde5d7be9357a7527093e6428ee1df4ddff2c5L17-R26): Refactored the `mockDatabaseConfig` and `mockDatabaseConfigWithoutWriteAndRead` functions to remove unused parameters (`prefix`, `singular`) and directly use the `Connection` attribute from `database.Config`. [[1]](diffhunk://#diff-e99a73045ad79e1cf1d850b270fde5d7be9357a7527093e …
> fix: [#706] Setting timezone in MySQL DSN (e.g., Asia/Shanghai) causes “invalid DSN” error

- foundation/application_test.go
- foundation/console/about_command.go
- foundation/console/about_command_test.go
- session/manager.go
- session/manager_test.go
- session/middleware/start_session.go
- session/middleware/start_session_test.go
Closes https://github.com/goravel/goravel/issues/707
This pull request updates the configuration key for session management across multiple files, replacing `"session.driver"` with `"session.default"`. This change ensures consistency in the naming convention and aligns with the updated configuration structure.
* [`foundation/application_test.go`](diffhunk://#diff-6557bfe8e38b58d9171f71a99a6402529163c1ebc89309419e4f62e5cf68855eL395-R395): Updated mock configuration in `TestMakeSession` to use `"session.default"` instead of `"session.driver"`.
* [`foundation/console/about_command.go`](diffhunk://#diff-ab50162808a2b574b9fbd0a4b8d5472e8637fbe4da3d903a07d68a282a97a147L106-R106): Modified `gatherApplicationInformation` to retrieve the session configuration using `"session.default"` instead of …
> feat: [#707] Change the configuration session.driver to session.default

- contracts/database/driver/grammar.go
- database/db/expression.go
- database/db/query.go
- database/db/query_test.go
- database/gorm/query.go
- errors/list.go
- mocks/database/driver/Grammar.go
- mocks/database/driver/JsonGrammar.go
Resolve https://github.com/goravel/goravel/issues/712
Resolve https://github.com/goravel/goravel/issues/713
When updating a JSON column, support use `->` syntax to update the appropriate key in the JSON object.
```go
facades.Orm().Query().Model(&models.User{}).Where("id", 1).Update("options->enabled", true)
facades.Orm().Query().Model(&models.User{}).Where("id", 1).Update("options->languages[0]", "en")
facades.Orm().Query().Model(&models.User{}).Where("id", 1).Update("options->languages", []string{"en", "de"})
facades.Orm().Query().Model(&models.User{}).Where("id", 1).Update(map[string]any{
"preferences->dining->meal": "salad",
"options->languages[0]":     "en",
"options->enabled":          true,
})
```
```go
facades.DB().Table("users").Where("id", 1).Update("options->enabled", true) …
```
> feat: [#712,#713] facades.Orm().Query() and facades.DB() Support Updating JSON Columns

- foundation/console/package_make_command_stubs.go
Closes https://github.com/goravel/goravel/issues/667
This pull request refactors the `ServiceProvider` class in `foundation/console/package_make_command_stubs.go` to consolidate multiple methods into a single `Relationship` method. This change simplifies the code and provides a more structured representation of bindings, dependencies, and services provided by the service provider.
* [`foundation/console/package_make_command_stubs.go`](diffhunk://#diff-48b92f03d2f63d7dacefd122b98e617f162c486470d7875e28ec8dbb9edd7bcfL40-L56): Replaced the `Bindings`, `Dependencies`, and `ProvideFor` methods with a single `Relationship` method, which returns a `binding.Relationship` object containing structured data for bindings, dependencies, and services provided.
> fix: [#667] package install typo

- support/database/database.go
- support/database/database_test.go
This pull request refines the `GetIDByReflect` function in `support/database/database.go` and its associated tests in `support/database/database_test.go`. The changes improve handling of nil values and enhance test descriptions for clarity. Additionally, redundant test cases have been removed to streamline the test suite.
* Updated the logic to check for `nil` values when recursively calling `GetIDByReflect` on anonymous struct fields. This ensures the function returns `nil` instead of proceeding with invalid data. (`[support/database/database.goL37-R40](diffhunk://#diff-385f411c58779199cd9530e6675be32f3332a63a70f9e3ad392e73882ab042a9L37-R40)`)
* Clarified test case descriptions in `TestGetID` to specify conditions under which values are returned or `nil` is expected. For example, …
> fix: the GetID function can't get id correctly

- auth/auth.go
- auth/auth_test.go
This pull request refactors the error handling logic in the `auth` package, transitioning from logging and returning `nil` to using `panic` for error propagation. This change simplifies the code and aligns error handling with the framework's `http recover` mechanism. Corresponding updates have been made to the test cases to validate this new behavior.
* [`auth/auth.go`](diffhunk://#diff-f5c9a39fac1719f2a73593994b931d8a874449548e8a3753e1be46e761e503eaL86-R99): Replaced calls to `r.log.Panic` with `panic` to rely on `http recover` for error handling, ensuring errors are propagated without redundant logging.
* [`auth/auth_test.go`](diffhunk://#diff-b06746870e62f95017714121be6134cffdc4bd1d46dd21f8cae8c484e3e2829dL97-R100): Removed expectations for `mockLog.Panic` and replaced them with …
> chore: optimize auth session log

- queue/failer.go
- support/convert/convert.go
- support/convert/convert_test.go
- support/convert/type.go
- support/convert/type_test.go
This pull request refactors the `ToAnySlice` function by relocating it from `support/convert/convert.go` to `support/convert/type.go`, along with its associated tests. The changes streamline the codebase and improve organization by grouping type-related utilities together.
* [`queue/failer.go`](diffhunk://#diff-e751df76a45505e9614e773c2a47e785de145a48662b9cafcb0f5b00bc1b01c8L47-R48): Updated the `Failer.Get` method to use the relocated `ToAnySlice` function for converting slices, simplifying the code.
* [`support/convert/convert.go`](diffhunk://#diff-3a492504b005a8bdf625fd4072ff43986a636adb7ab1af07bb66b161c969789fL82-L93): Removed the `ToAnySlice` function from this file as part of the relocation effort.
* [`support/convert/type.go`](diffhunk://#diff-ab2f6738140aafb039167fccdf916cd25b0c400 …
> chore: optimzie failer

- support/file/file.go
The extension can't be returned when judging some special files, eg: [test.unity3d.zip](https://github.com/user-attachments/files/21017007/test.unity3d.zip).
Can't add test cases for this scenario.
> fix: file.Extension

- auth/auth_test.go
- auth/jwt_guard.go
- auth/jwt_guard_test.go
- foundation/application_test.go
This pull request refactors how the TTL (time-to-live) configuration is handled in the JWT authentication system. The changes focus on removing the `getTtl` helper function and replacing its usage with direct calls to `GetInt` on the configuration object. Additionally, redundant test cases for `getTtl` have been removed.
* Replaced calls to `getTtl` with direct usage of `configFacade.GetInt` in `auth/jwt_guard.go`. Added fallback logic to ensure a default TTL of 100 years if no value is configured. (`[[1]](diffhunk://#diff-3e8e8c158483b45ef7d8c8fa7167074502a65962cf0a8bcd5abb5d4be828ec90L67-R75)`, `[[2]](diffhunk://#diff-3e8e8c158483b45ef7d8c8fa7167074502a65962cf0a8bcd5abb5d4be828ec90L309-L325)`)
* Updated test cases in `auth/auth_test.go` and `auth/jwt_guard_test.go` to use `GetInt` …
> chore: optimize jwt code

- database/gorm/event_test.go
- support/str/str.go
- support/str/str_test.go
- Fixed `ChopStart` and `ChopEnd` to match and remove exact strings instead of treating them as character sets (e.g., "hehe".chopStart("he") now returns "he").
- Escaped special characters in `Replace` when using case-insensitive mode to avoid incorrect regex behavior.
- Improved `Snake` case conversion to handle acronyms properly, e.g., `UserID` becomes `user_id` instead of `user_i_d`.
> fix: Refactor str package methods for better Replace and case handling

- database/db/query.go
- database/db/query_test.go
- database/gorm/query.go
- database/gorm/query_test.go
- support/deep/slice.go
Closes https://github.com/goravel/goravel/issues/732
The root reason is that the `append` function returns the same pointer as the original slice if the slice doesn't extend its space.
> fix: [#732] The query conditions may get messed up when reusing the query multiple times

- database/schema/schema.go
When uses Register several times to overrides the registered ones!
> fix: prevent overwriting existing migrations when registering new ones

- mail/application.go
> fix: cc and bcc fields not set when sending mail due to incorrect condition in SendMail (v1.16.x)

- mail/job.go
> fix: `SendMailJob` returns incorrect errors (v1.16.x)

- foundation/console/package_make_command_stubs.go
Closes https://github.com/goravel/goravel/issues/743
> fix: [#743] package make command generates correct code

- foundation/console/package_make_command_stubs.go
- foundation/console/vendor_publish_command.go
- foundation/console/vendor_publish_command_test.go
Closes https://github.com/goravel/goravel/issues/749
This pull request introduces improvements to the vendor publish command and its test coverage, along with minor code cleanups. The main changes include refining path handling logic, enhancing test coverage for error scenarios, and cleaning up unused imports.
**Vendor publish command improvements:**
* Removed redundant path normalization logic from the `Handle` method in `vendor_publish_command.go`, simplifying how target paths are processed.
**Test coverage enhancements:**
* Added new tests to `vendor_publish_command_test.go` to verify error handling when no vendor is found and when the package directory does not exist. These tests use a mock context to simulate command execution and error reporting.
* Integrated …
> fix: [#749] The path is incorrect when publishing package files

- config/application_test.go
- console/cli_helper.go
- console/console/build_command.go
- database/gorm/event.go
- database/gorm/query.go
- database/gorm/query_test.go
- database/gorm/test_models.go
- database/schema/schema_test.go
- database/service_provider.go
- filesystem/local.go
- log/formatter/general.go
- log/utils.go
- mail/mail.go
- support/debug/dump_test.go
- support/docker/container_manager.go
- support/docker/docker.go
- support/docker/utils.go
- support/file/file.go
- support/http/body.go
- support/http/body_test.go
- testing/file/file.go
- testing/file/file_test.go
- testing/test_response.go
- validation/validator_test.go
Closes https://github.com/goravel/goravel/issues/738
This pull request refines how ORM lifecycle events are triggered in the GORM query logic, especially for batch operations involving slices and mass deletes. The core improvement is to prevent event hooks from being triggered when the destination is a slice (for create, update, save, retrieve events) or when deleting/force-deleting mass records without a specific ID. This ensures event handlers only run for single-record operations, improving correctness and preventing unintended side effects. The test suite has been expanded to cover these new behaviors, and the event handler code has been updated to panic if the new constraints are violated, aiding debugging.
**Event Handling Logic Improvements:**
* Updated `database/gorm/query.go` so …
> fix: [#738] The Orm Creating event can be triggered when the query with the Model method

- console/console/build_command.go
- console/console/build_command_test.go
This update refactors the build command to provide an interactive selection for OS and architecture, limited to commonly used options for convenience. However, users can still specify any OS and architecture supported by Go via command-line arguments. The validation of os and arch values is now delegated to the Go compiler, ensuring flexibility while simplifying the command logic. This makes the build process user-friendly for most cases, while retaining full compatibility with all platforms supported by Go.
> feat: refactor build command to support interactive and custom OS/arch selection

- database/db/db.go
- database/orm/orm.go
- errors/errors.go
- go.mod
- go.sum
- support/constant.go
- tests/db_test.go
- tests/orm_test.go
Closes https://github.com/goravel/goravel/issues/762
This pull request improves the transaction handling logic in both the database and ORM layers to ensure that panics within transaction callbacks are safely caught and handled. Now, if a panic occurs during a transaction, the transaction will be rolled back and an error will be returned, preventing partial writes and improving reliability. The change is validated by new and updated tests for both layers.
**Transaction error handling improvements:**
* Updated `Transaction` methods in `database/db/db.go` and `database/orm/orm.go` to catch panics, rollback the transaction, and return a formatted error if a panic occurs. [[1]](diffhunk://#diff-116badc4071402f3e8ccbe2cbbc17c2954ad60d78fdf7e4bb0887a5b4ee3bf33L93-R109) …
> fix: [#762] handle panic when using transaction

- database/db/builder.go
- tests/db_test.go
- tests/go.mod
- tests/go.sum
Closes https://github.com/goravel/goravel/issues/768
This pull request introduces a new test case to verify database behavior when inserting and retrieving records with missing columns, and updates a dependency version in the test suite.
**Testing enhancements:**
* Added `TestInsert_First_Get_With_Missing_Columns` to `db_test.go` to ensure that inserting and retrieving a struct missing the `height` column works as expected, verifying correct handling of absent fields during database operations.
**Dependency updates:**
* Updated `github.com/go-viper/mapstructure/v2` from version `v2.3.0` to `v2.4.0` in `tests/go.mod` to bring in the latest improvements and fixes.
> fix: [#768] facades.DB will panic when migrating a new column

- contracts/database/orm/orm.go
- database/gorm/conditions.go
- database/gorm/query.go
- mocks/database/orm/Query.go
- tests/go.mod
- tests/go.sum
- tests/query_test.go
Closes https://github.com/goravel/goravel/issues/770
This pull request adds support for raw SQL selection in the ORM query interface, allowing more flexible and complex queries. The main changes include introducing a new `SelectRaw` method to the query interface and its implementation, updating the internal conditions structure to support raw selects, and adding corresponding tests and mocks.
**Raw SQL selection support:**
* Added `SelectRaw` method to the `Query` interface in `orm.go`, enabling users to specify raw SQL queries for field selection.
* Implemented the `SelectRaw` method in `query.go`, updated the `Conditions` struct to include the new `selectRaw` field, and added the `Select` struct to hold the query and its arguments. …
> feat: [#770] Add a SelectRaw function for the ORM

- http/middleware/verify_csrf_token_test.go
> fix: verify csrf token tests

- auth/service_provider.go
- contracts/binding/binding.go
- database/service_provider.go
- database/setup/setup.go
- foundation/application.go
- foundation/console/package_install_command.go
- foundation/console/package_install_command_test.go
- http/service_provider.go
- route/setup/setup.go
- route/setup/stubs.go
- schedule/setup/setup.go
- support/binding/binding.go
- support/binding/binding_test.go
- support/collect/collect.go
- support/collect/collect_test.go
1. Add `facades.Schema().Register(database.Kernel{}.Migrations())` and `facades.Seeder().Register(database.Kernel{}.Seeders())` when installing `Schema` and `Seeder` facades.
2. Fix the cycle import error in the database service provider file given Schema depends on Orm.
3. Add `welcome.tmpl` when installing `Route`.
> feat: [#612] Optimize install DB

- console/cli_context.go
- console/cli_context_test.go
- contracts/console/command.go
- mocks/console/Context.go
Closes https://github.com/goravel/goravel/issues/729
Added some helper methods requested in the issue
> feat: add helper methods for console
