contracts/route/route.go, go.mod, http/gin_context.go, http/middleware/cors.go, route/gin.go, support/constant.go
=> Upgrade v1.3.0

contracts/filesystem/mocks/Driver.go, contracts/filesystem/mocks/File.go, contracts/filesystem/mocks/Storage.go, contracts/filesystem/storage.go, filesystem/cos.go, filesystem/local.go, filesystem/oss.go, filesystem/s3.go, filesystem/utils.go, support/constant.go
Add facades.Storage.Files, facades.Storage.AllFiles, facades.Storage.Directories, facades.Storage.AllDirectories;
=> Upgrate 1.6.1

filesystem/local.go, foundation/application.go, foundation/path.go, support/constant.go
1. Fix facades.Storage.Path error;
=> Upgrate v1.6.3

crypt/application_test.go, hash/application_test.go
=> Improve unit tests

contracts/http/method.go
Close https://github.com/goravel/goravel/issues/97
=> Add net/http Method map to contracts/http

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/welcome.yml
=> Optimize template

go.mod, go.sum, route/gin_group.go, route/gin_group_test.go
=> Fix middleware bug

http/gin_context.go, http/gin_request.go, route/gin_test.go, support/constant.go
Close: https://github.com/goravel/goravel/issues/136
=> Fix: [#136] Fix input bind conflict

foundation/console/vendor_publish_command.go, foundation/console/vendor_publish_command_test.go
```
func (receiver *ServiceProvider) Boot(app foundation.Application) {
app.Publishes("./packages/sms", map[string]string{
"config": app.ConfigPath(""),
})
}
```
=> Feat: vendor:publish command supports publish directory

schedule/application.go, schedule/application_test.go, schedule/support/event.go, schedule/support/event_test.go, support/constant.go
Close https://github.com/goravel/goravel/issues/148: schedule will panic and stop when Artisan command returns error
Close https://github.com/goravel/goravel/issues/150: 任务调度 DailyAt 每分钟都会执行
Will release v1.11.3
=> Fix: [#148][#150] 

cache/application.go, cache/driver.go, cache/driver_test.go, cache/service_provider.go
Add a new style to cache custom driver: `func() (filesystem.Driver, error)`
=> Feat: Optimize cache custom driver

database/console/migrate_refresh_command.go, database/console/migrate_refresh_command_test.go, database/console/migrate_rollback_command.go, database/console/migrate_rollback_command_test.go, database/console/model_make_command_test.go, database/console/observer_make_command_test.go
Add step option to the migrate refresh command
=> Add step option to the migrate refresh command

config/service_provider.go, foundation/application.go
There is an error on the Carbon module.
=> Fix: Set timezone error

support/carbon/json.go
=> Feat: Add New* for Carbon

support/constant.go
=> Upgrade v1.12.0

auth/console/jwt_secret_command.go, console/console/key_generate_command.go, filesystem/application_test.go, filesystem/file.go, filesystem/file_test.go, filesystem/utils.go, foundation/console/vendor_publish_command.go, foundation/console/vendor_publish_command_test.go, foundation/path.go, http/gin_request.go, log/logger/daily.go, log/logrus_writer.go, route/gin_test.go, support/file/file.go
Closes goravel/goravel#181
Fix path error in Windows and optimize code.
none.
=> fix: path error in Windows

cache/driver.go, database/gorm/query_test.go, database/gorm/test_utils.go, filesystem/application.go, foundation/application_test.go, foundation/console/package_make_command_stubs.go, foundation/container.go, support/constant.go, testing/docker/docker.go, testing/docker/redis.go
=> Fix: MakeGate error

http/service_provider.go
=> Fix Http Service provider Typo

crypt/aes.go, go.mod, go.sum, http/gin_request.go, log/formatter/general.go, route/gin_test.go, support/carbon/json_test.go
Use sonic to json serializing and deserializing
none
=> feat: use sonic to json serializing and deserializing

http/service_provider.go, support/constant.go
Closes https://github.com/goravel/goravel/issues/197
Fix throttle middleware panic
=> Feat: Fix throttle middleware panic

.github/workflows/cr.yml, .github/workflows/pr-check-title.yml
workflow: optimize cr and title check
=> workflow: optimize cr and title check

README.md, README_zh.md
=> docs: optimize README

.github/dependabot.yml
=> workflow: optimize dependabot

contracts/schedule/event.go, contracts/schedule/mocks/Event.go, schedule/application.go, schedule/application_test.go, schedule/event.go, schedule/event_test.go, schedule/service_provider.go
Closes https://github.com/goravel/goravel/issues/178
facades.Schedule() supports scale horizontally
=> feat: facades.Schedule() supports scale horizontally

config/application.go, config/application_test.go
当`.env`文件和主程序不在同一个目录时，使用`--env=`自定义配置路径报错：
```
Invalid Config error: Config File "/www/xxx/.env" Not Found in "[/root]"
```
这个 PR 修复此问题。
=> fix: env file read

contracts/database/factory/factory.go, database/factory.go, database/factory_test.go, database/gorm/query_test.go, database/orm.go
Closes https://github.com/goravel/goravel/issues/215
Factory can't fill data to nested struct
=> fix: [#215] [Bug] Factory can't fill data to nested struct

http/console/stubs.go
=> fix: controller sub

auth/auth.go, auth/auth_test.go, go.mod, go.sum
=> fix: jwt Parse problem

support/constant.go
=> Upgrade v1.12.6

validation/validator.go, validation/validator_test.go
Closes https://github.com/goravel/goravel/issues/229
=> fix: [#229] media file not parsing correctly

.github/workflows/test.yml
=> workflow(test): update go 1.21

.github/workflows/test.yml, go.mod
=> feat: update go 1.20

http/middleware/throttle.go, http/middleware/throttle_test.go, http/service_provider.go
Closes # 
The [opentracing](https://github.com/goravel/http-middleware/blob/master/opentracing.go) middleware is removed from goravel/framework, because I think there are not many people using it, but goravel/framework adds more extra packages if contains it, so Users can add it themselves if needed.
=> feat: Add throttle middleware

database/gorm/query_test.go, go.mod, go.sum, support/carbon/carbon.go, support/carbon/json.go
=> feat: Upgarde the carbon package

http/context.go, http/context_test.go
=> feat: Add the http.Background() method

README.md, README_zh.md, support/constant.go, testing/mock/mock.go
=> feat: Optimize mock

support/constant.go
=> chore: Upgrade v1.13.1

filesystem/local.go, filesystem/local_test.go
Closes https://github.com/goravel/goravel/issues/263
=> fix: [#263] There is a path error in the filesystem module

database/db/dsn.go, database/db/dsn_test.go, database/gorm/dialector_test.go, database/gorm/utils_test.go, go.mod
Closes https://github.com/goravel/goravel/issues/270
=> fix: [#270] Optimize postgres DNS

database/gorm/cursor.go, database/gorm/event.go, database/gorm/event_test.go, database/gorm/query.go, database/gorm/query_test.go, database/gorm/transaction.go
Closes https://github.com/goravel/goravel/issues/253
=> fix: [#253] [Bug] The With method can't be used with the Cursor method together

README.md, README_zh.md, config/application.go, config/application_test.go, database/db/dsn.go, database/db/dsn_test.go, database/gorm/cursor.go, database/gorm/dialector_test.go, database/gorm/event.go, database/gorm/event_test.go, database/gorm/query.go, database/gorm/query_test.go, database/gorm/transaction.go, database/gorm/utils_test.go, event/application.go, support/constant.go, support/database/database.go
=> chore: merge v1.13.x to master

config/application.go, config/application_test.go, foundation/application.go, support/constant.go
=> feat: [#265] The Config module supports get system environment variables

testing/mock/log.go
Closes https://github.com/goravel/goravel/issues/320
=> fix: [#320] mock.Log() is not working

support/constant.go
=> release: Upgrade v1.13.5

queue/application_test.go, queue/task.go
Closes https://github.com/goravel/goravel/issues/341
=> fix: [#341] The Chain Query isn't executed one by one

.github/workflows/codecov.yml, testing/mock/log.go
=> fix: log mock

contracts/database/orm/orm.go, database/gorm/query.go, database/gorm/query_test.go, mocks/database/orm/Query.go, mocks/database/orm/Transaction.go
=> feat: add OrWhereNull method

mail/application_test.go, queue/application.go, queue/application_test.go, queue/log.go, queue/machinery.go, queue/machinery_test.go, queue/service_provider.go, queue/task.go, queue/worker.go
Closes https://github.com/goravel/goravel/issues/389
=> feat: [#389] The queue log needs to be controled by APP_DEBUG

log/formatter/general.go
Closes https://github.com/goravel/goravel/issues/395
=> fix: the new line print of Log is incorrect

foundation/console/vendor_publish_command.go, foundation/console/vendor_publish_command_test.go, support/constant.go
Closes https://github.com/goravel/goravel/issues/345
=> fix: [#345] app.Publishes is not working for directory

auth/auth.go, auth/auth_test.go, database/gorm/event.go, database/gorm/query.go, database/orm.go, database/orm_test.go, foundation/console/vendor_publish_command.go, foundation/console/vendor_publish_command_test.go, log/formatter/general.go, mail/application_test.go, queue/application.go, queue/application_test.go, queue/log.go, queue/machinery.go, queue/machinery_test.go, queue/service_provider.go, queue/task.go, queue/worker.go, support/constant.go
=> merge: v1.13.9

database/gorm/event.go, database/gorm/event_test.go, database/gorm/query_test.go, database/gorm/test_models.go
Closes https://github.com/goravel/goravel/issues/405
=> fix: [#405] The GetAttribute of orm event returns an error value when getting id

README.md
=> docs: fix typo readme links

support/carbon/carbon.go
Closes https://github.com/goravel/goravel/issues/241
=> feat: use golang-module/carbon's SetTestNow method

testing/mock/mock.go
=> feat: add app mock

testing/mock/mock.go
=> feat: add context mock

contracts/http/response.go, http/middleware/throttle_test.go, log/logrus_writer_test.go, mocks/http/ContextResponse.go, session/middleware/start_session_test.go
=> chore: Remove ResponseSuccess

contracts/http/response.go, testing/mock/mock.go
=> chore: add response mock

contracts/http/response.go, http/middleware/throttle_test.go, log/logrus_writer_test.go, mocks/http/ContextResponse.go, session/middleware/start_session_test.go
Closes https://github.com/goravel/goravel/issues/275
=> feat: [#275] Add a new NoContent() method for Response

console/cli_context.go
=> feat: Add bottom help bar for multiselect

.github/workflows/test.yml, translation/file_loader_test.go, translation/service_provider.go
=> fix: lang path

.github/workflows/test.yml, session/middleware/start_session.go, support/constant.go, translation/file_loader_test.go, translation/service_provider.go, translation/translator_test.go
=> merge: v1.14.1

foundation/application_test.go, go.mod, go.sum, schedule/application.go, schedule/application_test.go, schedule/logger.go, schedule/service_provider.go
Closes https://github.com/goravel/goravel/issues/443
=> feat(schedule): optimize log print

support/constant.go, validation/validator.go, validation/validator_test.go
=> merge v1.14.2

session/driver/file.go, session/driver/file_test.go, support/constant.go, validation/validation.go, validation/validator.go, validation/validator_test.go
=> merge: v1.14.3

http/console/stubs.go
=> fix: add Filters for request make

foundation/application_test.go, session/manager.go, session/manager_test.go, session/middleware/start_session_test.go
=> fix: session driver lock problem

contracts/http/request.go, http/middleware/throttle_test.go, log/logrus_writer_test.go, mocks/http/ContextRequest.go, session/middleware/start_session_test.go
Closes https://github.com/goravel/goravel/issues/338
=> feat: [#338] Support c.Request().BindQuery to bind query params to a struct

session/middleware/start_session.go, session/middleware/start_session_test.go, session/service_provider.go
Closes https://github.com/goravel/goravel/issues/457
=> feat: [#457] Remove session lottery config

foundation/application.go
…will not take effect in artisan console
=> fix: bootArtisan should be called last, otherwise the settings after that will not take effect in artisan console

contracts/route/route.go, foundation/application.go, mocks/route/Route.go
=> merge: v1.14.5

auth/auth_test.go, contracts/http/context.go, http/context.go, http/context_test.go, http/middleware/throttle_test.go, mocks/http/Context.go, session/middleware/start_session_test.go, support/constant.go
=> merge: v1.14.7

session/driver/file.go
=> perf: optimize session file driver

database/gorm/query_test.go, database/gorm/test_utils.go, mocks/http/Context.go
=> chore: Add test cases for orm

contracts/route/route.go, mocks/route/Route.go
=> add test method to route

event/application.go, event/application_test.go
Closes https://github.com/goravel/goravel/issues/523
Tested in https://github.com/goravel/example/pull/33
=> fix: [#523] [Bug] The same listener can not be registered by multiple events, framework will threw an error: job signature duplicate

contracts/log/log.go, log/application.go, log/entry.go, log/logrus_writer.go, log/logrus_writer_test.go, mocks/log/Entry.go, support/constant.go
Closes https://github.com/goravel/goravel/issues/531
Tested locally, it's hard to add a  test case:
=> fix: [#531] An extra log will be printed when using a custom log driver

validation/options.go, validation/validation_test.go
=> feat: [#517] Optimize PrepareForValidation method

database/schema/processors/sqlite.go, database/schema/processors/sqlite_test.go, database/schema/schema_test.go
Sqlite columns don't return TypeName previously.
=> fix: sqlite processor

foundation/console/about_command.go, foundation/console/about_command_test.go
=> chore: Improve artisan about commmand unit test

console/application.go, console/application_test.go, console/cli_helper_test.go, console/service_provider.go
=> fix: artisan bug (#802)

grpc/application.go
=> chore: optimize grpc link

tests/go.mod, tests/go.sum, tests/main_test.go
=> test: submodule

contracts/database/schema/blueprint.go, contracts/database/schema/grammar.go, database/schema/blueprint.go, database/schema/blueprint_test.go, database/schema/grammars/mysql.go, database/schema/grammars/mysql_test.go, database/schema/grammars/postgres.go, database/schema/grammars/postgres_test.go, database/schema/grammars/sqlite.go, database/schema/grammars/sqlite_test.go, database/schema/grammars/sqlserver.go, database/schema/grammars/sqlserver_test.go, database/schema/schema_test.go, mocks/database/schema/Blueprint.go, mocks/database/schema/Grammar.go
Add bool type for migration,like 
```go
table.Boolean("is_name").Default(true)
```
Closes https://github.com/goravel/goravel/issues/578?
=> feat: [#578] Add bool type for migration

database/schema/utils.go, database/schema/utils_test.go
=> chore: [#540] Add common functions

contracts/database/schema/grammar.go, database/schema/schema.go, database/schema/wrap.go, database/schema/wrap_test.go, go.mod, go.sum, mocks/database/schema/Grammar.go
https://github.com/goravel/goravel/issues/540
=> feat: [#540] Adapt Mysql driver

tests/go.mod, tests/go.sum
=> chore(deps): Update tests module

contracts/database/schema/blueprint.go, contracts/database/schema/grammar.go, database/schema/blueprint.go, mocks/database/schema/Blueprint.go, mocks/database/schema/Grammar.go, tests/schema_test.go
Add Table Comment Support in Go Migrator
Closes https://github.com/goravel/goravel/issues/549
=> feat: [#549] migrator supports table comments

database/gorm/query.go
=> chore: optimize return values in GORM BuildQuery method

database/db/query.go, database/db/query_test.go, tests/db_test.go
=> feat: implement nested where

.coderabbit.yaml, contracts/database/db/db.go, database/db/query.go, database/db/query_test.go, errors/list.go, mocks/database/db/Query.go, tests/db_test.go, tests/models.go, tests/query.go, tests/table.go
=> feat: [#358] add some Where methods

contracts/database/db/db.go, database/db/conditions.go, database/db/query.go, database/db/query_test.go, mocks/database/db/Query.go
=> feat: [#358] Implement OrderBy

codecov.yml, contracts/database/db/db.go, contracts/database/orm/orm.go, database/db/conditions.go, database/db/query.go, database/db/query_test.go, database/gorm/conditions.go, database/gorm/query.go, mocks/database/db/Query.go, mocks/database/orm/Query.go, tests/db_test.go, tests/query_test.go
=> feat: [#358] Implement GroupBy, Having, Join methods

contracts/foundation/application.go, database/orm/orm.go, foundation/container.go, foundation/container_test.go, http/middleware/throttle.go, mocks/foundation/Application.go, support/constant.go
We need to refresh all modules when testing in goravel/example with different drivers.
=> feat: optimize refresh method

mail/application_test.go
=> fix: mail test

console/cli_context.go, console/console/build_command.go, console/console/build_command_test.go, console/console/key_generate_command.go, console/console/key_generate_command_test.go, contracts/console/command.go, database/console/wipe_command_test.go, foundation/console/env_decrypt_command.go, foundation/console/env_decrypt_command_test.go, foundation/console/env_encrypt_command.go, foundation/console/env_encrypt_command_test.go, mocks/console/Context.go, support/console/console.go, support/console/console_test.go
Closes https://github.com/goravel/goravel/issues/640
=> feat: [#640] Optimize console ctx.Confirm method

contracts/http/request.go, log/logrus_writer_test.go, mocks/http/ContextRequest.go, session/middleware/start_session_test.go
Closes https://github.com/goravel/goravel/issues/376
=> feat: [#376] ctx.Request() supports get multiple files directly

auth/auth.go, auth/auth_test.go, auth/jwt_guard.go, auth/jwt_guard_test.go, auth/orm_user_provider.go, auth/orm_user_provider_test.go, auth/service_provider.go, contracts/auth/auth.go, contracts/foundation/application.go, errors/list.go, facades/auth.go, foundation/application_test.go, foundation/container.go, mocks/auth/Auth.go, mocks/auth/GuardFunc.go, mocks/auth/UserProvider.go, mocks/auth/UserProviderFunc.go, mocks/foundation/Application.go
This pull request includes significant changes to the `auth` package, focusing on refactoring the authentication system and improving the JWT guard implementation. The most important changes include restructuring the `Auth` and `JwtGuard` classes, updating the `OrmUserProvider`, and adding new tests for the `OrmUserProvider`.
* [`auth/auth.go`](diffhunk://#diff-f5c9a39fac1719f2a73593994b931d8a874449548e8a3753e1be46e761e503eaR5-R99): Refactored the `Auth` class to use `sync.Map` for storing guard and provider functions, removed unused dependencies, and simplified the constructor by eliminating the need for `cache` and `orm` parameters. Added `log` as a new dependency.
* [`auth/jwt_guard.go`](diffhunk://#diff-3e8e8c158483b45ef7d8c8fa7167074502a65962cf0a8bcd5abb5d4be828ec90R19-R30): …
=> feat: optimize facades.Auth().Guard() return value

foundation/console/package_install_command_test.go, foundation/console/package_uninstall_command_test.go
=> chore: add unit tests for package:install and package:uninstall commands

support/carbon/carbon.go
The following screenshot is `golang` official comment format
=> feat: Refer to `https://pkg.go.dev/time` for unified comment format

support/constant.go
This pull request includes a minor version update to the `support/constant.go` file. The change updates the version string from "v1.15.6" to "v1.15.7".
* [`support/constant.go`](diffhunk://#diff-1c87bd002c9aea504d2cd4ef42e1ab6b85d3077f23be1cd269b39981c13c0cb5L3-R3): Updated the `Version` constant from "v1.15.6" to "v1.15.7".
=> upgrade: v1.15.7

packages/match/match.go, packages/modify/actions_test.go, packages/modify/utils.go
=> chore: refactor expr parser to keep comments

errors/list.go, packages/match/helper.go, packages/match/helper_test.go, queue/console/job_make_command.go, queue/console/job_make_command_test.go, queue/console/job_stubs.go
=> feat: auto-register quque job when created via CLI

foundation/application.go, log/application_test.go, log/formatter/general.go, log/formatter/general_test.go, log/logrus_writer_test.go
Closes https://github.com/goravel/goravel/issues/644
=> fix: [#664] resolve date mismatch between log file name and log entries

console/cli_context.go, console/cli_context_test.go, contracts/queue/config.go, log/formatter/general.go, log/formatter/general_test.go, mocks/queue/Config.go, queue/application.go, queue/config.go, queue/config_test.go, queue/driver_sync_test.go, queue/pending_job.go, queue/pending_job_test.go, queue/worker.go, queue/worker_test.go, support/console/console.go, support/console/console_test.go
This pull request introduces several updates across the codebase, focusing on refactoring, improving logging, and enhancing modularity. The most significant changes include splitting the `Default` method in the queue configuration into more granular methods, adding detailed logging for worker tasks, and refactoring the `TwoColumnDetail` logic into a reusable utility function.
=> feat: optimize queue log

support/console/execute.go, support/console/execute_test.go
=> chore: add support for custom spinner messages in ExecuteCommand

contracts/foundation/application.go, database/orm/orm.go, database/service_provider.go, foundation/application.go, foundation/container.go, foundation/container_test.go, mocks/foundation/Application.go
Closes https://github.com/goravel/goravel/issues/672
This pull request introduces several changes across multiple files to improve code consistency, enhance functionality, and simplify maintenance. The most significant updates include centralizing binding constants, refactoring service provider methods for clarity, adding new functionalities to caching and database interfaces, and enhancing test cases for better maintainability.
* Introduced a new `contracts/binding.go` file to centralize all binding constants, replacing hardcoded string bindings across the codebase.
* Updated service providers (`auth`, `cache`, `config`, `console`, `crypt`) to use the centralized binding constants for cleaner and more maintainable code. [[1]](diffhunk://#diff-faba8a1cabb0419011050fd2532760609b9e5bf01b5140 …
=> fix: [#672] facades.Orm() doesn't refresh after calling facades.Testing().Docker().Database()

contracts/database/driver/column.go, database/console/table_command.go, database/console/table_command_test.go, database/schema/column.go, mocks/database/driver/ColumnDefinition.go
Closes https://github.com/goravel/goravel/issues/669
```go
schema.Create("postgres_generated_as", func(table contractsschema.Blueprint) {
table.ID()
table.String("name")
table.Integer("small_integer").GeneratedAs()
table.BigInteger("integer").GeneratedAs("START WITH 10 INCREMENT BY 2")
table.SmallInteger("big_integer").GeneratedAs("START WITH 20 INCREMENT BY 5").Always()
})
```
=> feat: [#669] Migration support GENERATED

contracts/schedule/event.go, mocks/schedule/Event.go, schedule/application.go, schedule/event.go, schedule/event_test.go
Closes https://github.com/goravel/goravel/issues/690
=> feat: [#690] enhance schedule method and resolve issue with second-level cron jobs on OnOneServer

tests/models.go, tests/query_test.go, tests/table.go
Closes https://github.com/goravel/goravel/issues/705
=> chore: [#1074] add unit tests for JSON queries

auth/auth_test.go, auth/jwt_guard.go, auth/jwt_guard_test.go, foundation/application_test.go
Closes https://github.com/goravel/goravel/issues/677
=> feat: [#677] Use guard specific secret and ttl for jwt_guard

route/console/route_list_command.go, route/console/route_list_command_test.go, route/service_provider.go
Closes https://github.com/goravel/goravel/issues/716
=> feat: [#716] support artisan route:list command

contracts/route/route.go, go.mod, log/utils_test.go, route/console/route_list_command.go, route/console/route_list_command_test.go, schedule/console/list_command.go, support/debug/func.go, support/debug/func_test.go
Closes https://github.com/goravel/goravel/issues/717
=> feat: [#717] support displaying handler names in artisan route:list command

database/db/logger.go, database/driver/gorm.go
Closes https://github.com/goravel/goravel/issues/682
Gorm can reconnect automatically, it's hard to add a test case for this, tested it locally:
=> feat: [#682] Automatically reconnect to database when connection is lost, including on startup or runtime interruptions

go.mod, go.sum, support/debug/dump.go, support/debug/dump_test.go, support/debug/func_test.go
Closes https://github.com/goravel/goravel/issues/721
=> feat: [#721] use godump instead of go-spew for better formatted output

support/carbon/carbon.go, support/carbon/carbon_test.go
- Change parameter of `New` function to optional parameter
- Unify function comment format
=> refactor: Change parameter of `New` function to optional parameter

support/convert/convert.go, support/convert/convert_test.go
Closes https://github.com/goravel/goravel/issues/722
=> feat: add ToAnySlice helper

foundation/console/package_make_command.go, foundation/console/package_make_command_test.go, support/file/file.go
This pull request introduces changes to improve the organization of generated package files and refactors the file content retrieval logic for better reusability. The most important changes include updating the directory structure for configuration files and extracting a reusable method for retrieving package content.
* [`foundation/console/package_make_command.go`](diffhunk://#diff-c3307427d10ac3485f2a5c50b92defb9927cda6d4773053923fffd71f0452df7L78-R80): Updated the directory structure for configuration files by moving them to a `setup/config` subdirectory and added a new `setup/setup.go` file to the generated package structure. (`[foundation/console/package_make_command.goL78-R80](diffhunk://#diff-c3307427d10ac3485f2a5c50b92defb9927cda6d4773053923fffd71f0452df7L78-R80)`)
* …
=> chore: optimize package config path

packages/modify/actions.go, packages/modify/actions_test.go, schedule/application_test.go
`goravel/app/jobs` is duplicated when running `make:job`:
=> fix: AddImport

errors/list.go, schedule/application_test.go, translation/fs_loader.go, translation/fs_loader_test.go, translation/service_provider.go, translation/translator.go, translation/translator_test.go
Optimize the `/lang/lang` folder to `/lang`:
=> feat: optimize fs loader

go.mod, go.sum, support/debug/dump.go, support/debug/dump_test.go
Related https://github.com/goravel/framework/pull/1105
Resolved the issues mentioned in this  [comment](https://github.com/goravel/framework/pull/1105#issuecomment-3022142564)
=> chore: Update module github.com/goforj/godump

contracts/http/method.go, contracts/http/request.go, contracts/route/route.go, mocks/http/ContextRequest.go, mocks/route/Route.go, route/console/route_list_command.go, route/console/route_list_command_test.go
Closes https://github.com/goravel/goravel/issues/728
Add two new methods:
```go
ctx.Request().Info()
ctx.Request().Name()
```
=> feat: [#728] add http.Info and http.Name methods

mail/job.go
=> fix: `SendMailJob` returns incorrect errors (v1.15.x) 

mail/job.go
=> fix: `SendMailJob` returns incorrect errors

go.mod, go.sum, support/debug/dump_test.go
=> chore: Update module github.com/goforj/godump to v1.6.0

foundation/console/package_install_command_test.go
This optimization resolves assertion failures encountered with Go 1.25 in the package installation test.
=> chore: optimize assertions for package installation

config/application_test.go, database/db/query.go, database/gorm/query.go, errors/errors.go, filesystem/local.go, http/client/response.go, support/file/file.go, support/http/body.go, support/http/body_test.go, support/process/utils.go, testing/file/file.go, testing/http/test_response.go, tests/container.go, tests/models.go, tests/query_test.go, validation/validator_test.go
Closes https://github.com/goravel/goravel/issues/738
=> fix: [#738] The Orm Creating event can be triggered when the query with the Model method

database/setup/setup.go, database/setup/stubs.go
=> feat: install DB,Orm,Schema,Seeder facades

event/setup/setup.go, event/setup/stubs.go, filesystem/setup/setup.go, filesystem/setup/stubs.go
=> feat: install Event, Storage facades

http/middleware/verify_csrf_token.go
=> fix: csrf token not included in header

console/console/make_command.go, console/console/make_command_test.go, console/console/stubs.go, contracts/packages/modify/modify.go, mocks/packages/modify/GoFile.go, packages/match/helper.go, packages/match/helper_test.go, packages/match/match.go, packages/modify/actions.go, packages/modify/actions_test.go, packages/modify/modify.go, packages/modify/modify_test.go, schedule/setup/setup.go, support/file/file_test.go, support/file/options.go, support/stub/stub.go
This pull request introduces enhancements and refactoring to the Goravel console command generation system, focusing on automating kernel initialization, improving code modification utilities, and expanding unit test coverage. The changes ensure that the console kernel and its registration in the service provider are automatically created and updated when generating new commands, reducing manual setup and potential errors. The modification utilities are extended to support more flexible and robust Go code manipulation, and new tests are added to verify these behaviors.
1. When creating a command via the `make:command` command, create the `app/console/kernel.go` file if not exist, and register the kernel in `app_service_provider.go`.
2. …
=> feat: optimize install schedule

contracts/binding/binding.go, database/setup/stubs.go
=> feat: [#612] Optimize install Database
